app:
  name: GOCRAWLER-WEB-SAMPLE
  environment: development
  host: 0.0.0.0
  debug: true
  port: 7000
  protocol: https
mongodb:
  dbName: "gocrawler-database"
  connection: "mongodb://localhost:27017/?readPreference=primary&directConnection=true&ssl=false"